mozilla-releng/build-puppet

modules/buildbot_bridge/files/requirements.txt, modules/buildbot_bridge2/files/requirements.txt, modules/buildmaster/files/db_maintenance_requirements.txt, modules/buildmaster/files/queue_requirements.txt, modules/cruncher/files/allthethings_requirements.txt, modules/cruncher/files/slave_health_requirements.txt, modules/releaserunner/files/requirements.txt, modules/selfserve_agent/files/requirements.txt, modules/signingworker/files/requirements.txt, modules/slaveapi/files/requirements.txt, modules/slaverebooter/files/requirements.txt
Most of this looks really safe - buildbot bridge2 has the most notable upgrade (big mysql-connector version change). If anything goes wrong with its upgrades, we can probably just rollback and not bother, since it dies with Buildbot.
=> Update dependencies for non-signing server, non-scriptworker machines.

modules/selfserve_agent/files/requirements.txt
It was replaced with setuptools a long time ago, which gets installed when the virtualenv is created.
=> Don't install distribute with selfserve_agent

modules/buildbot_bridge2/files/requirements.txt, modules/buildbot_bridge2/manifests/init.pp
I noticed that none of the upgrades were happening, which was because of the typo in the manifest, and then when the upgrades did happen, we had some bustage rooted in the Taskcluster upgrade. I've pinned the necessary packages to hold things at stable versions.
=> Fix issues with bbb2.

modules/releaserunner/files/requirements.txt
Looks like urllib3 was missing from the requirements.txt for releaserunner when it was first implemented in f5a07cb7e4338ebc187b8bcdc709a02c098e4b90. We have urllib3 in modules/releaserunner3/files/requirements.txt already, so we didn't hit any bustage there.
=> Bug 1467002 - urllib3 missing from releaserunner virtualenv

modules/signingworker/files/requirements.txt
[Bug 1467067](https://bugzilla.mozilla.org/show_bug.cgi?id=1467067) for more details - tl;dr is that current requests doesn't like the headers we give it for partial and source signing.
This can be a temporary downgrade until https://github.com/taskcluster/taskcluster-client.py/issues/107 is resolved by a new release there.
=> Bug 1467067 - ESR52 signing issues with int values for Content-Length

modules/buildslave/manifests/install.pp
I have no idea why this started to happen all of a sudden. Looking over old logs shows Twisted installing just fine without gcc. In any case, this should fix it.
=> Require gcc to be installed before creating buildslave virtualenv.

modules/releaserunner/files/requirements.txt, modules/releaserunner/manifests/services.pp
I tested this on bm83 as much as possible (I had to hack out a bunch of checks to get as far as task submission). Notable problems/fixes:
* The latest taskcluster library doesn't support encrypted vars
* Had to install pyasn1 for pgpy
* Had to downgrade "six" for pgpy to work (see https://github.com/SecurityInnovation/PGPy/issues/217)
In the end, I was able to get a graph created. I can't guarantee 100% that this will work in production because of all the hacks that I did, but I think this is as well tested as it's going to get.
=> Upgrade as much of releasetasks as we can

modules/releaserunner/files/requirements.txt
Found this on bm81 -- this is something that only the ancient release runner uses, which is why it didn't show up in my dev testing.
=> Add last missing requirement for releaserunner

README.md, manifests/moco-config.pp, modules/config/manifests/base.pp, modules/generic_worker/templates/generic-worker.config.erb, modules/puppet/templates/puppet-darwin-run-puppet.sh.erb, setup/common/install-puppetize.erb, setup/preseed/preseed_to_puppet.sh
This rewrites the remaining traces of https://hg.mozilla.org/build/puppet, and the original github location to the new, final home in the RelEng org.
@davehouse - I'm flagging you for review because of the changes to `puppet-darwin-run-puppet.sh.erb`. You'll notice that I've basically disabled the manifest version check for now. I'll need to make changes to the Puppet masters before we can enable it again. How important is that check?
=> Rewrite puppet manifest locations to the mozilla-releng org on Github.

modules/generic_worker/manifests/init.pp, modules/generic_worker/templates/generic-worker.config.erb, modules/generic_worker/templates/proxy-httpd.conf.erb, modules/packages/manifests/mozilla/generic_worker.pp
- changed the generic-worker version
- added version tag for tasckcluster-proxy
- Added an exect block to generate generic-worker signingKey
- changed generic-worker config file by add information for tasckcluster-proxy
- installed tasck-cluster proxy on /usr/local/bin location
- added proxy httpd file, to redirect curl http://taskcluster to port 8080 (taskcluster-proxy listen on this port)
=> Upgrade mac taskcluster workers to generic worker 10.8.4

.taskcluster.yml, modules/aws_manager/files/requirements.txt, modules/buildbot_bridge2/files/requirements.txt, modules/buildduty_tools/files/requirements.txt, modules/cruncher/files/slave_health_requirements.txt, modules/releaserunner/files/requirements.txt, modules/selfserve_agent/files/requirements.txt, modules/signingworker/files/requirements.txt, modules/slaveapi/files/requirements.txt, modules/slaverebooter/files/requirements.txt, test/verify-requirements.sh
This should implement the verifications suggested in https://bugzilla.mozilla.org/show_bug.cgi?id=1467255. Specifically, it:
* Adds hashes to requirements files (except the nodownload ones)
* Verifies requirements files with `pip install`.
In testing this I found a great deal of missing transitive dependencies. Evidently, they don't break anything, but they are part of the requirements so we should be installing them.
You'll notice I'm adding a .taskcluster.yml instead of adding things to .travis.yml. It didn't look like there was a great way to ensure the required system dependencies were installed in Travis, so I thought using Taskcluster + Docker would be easier - arguably we should be transitioning more stuff to Taskcluster anyways.
I wasn't able to get the Taskcluster hook working …
=> bug 1467255: Add verification of requirements files in CI

modules/pushapk_scriptworker/files/requirements.txt
This lets Firefox Focus use dedicated Google Play tracks
=> pushapk_scriptworker: Bump pushapkscript and mozapkpublisher for Focus

modules/fw/manifests/networks.pp, modules/fw/manifests/profiles/linux_taskcluster_worker.pp, modules/roller/manifests/systemd.pp, modules/roller/templates/dev/docker-compose.yml.erb, modules/roller/templates/prod/docker-compose.yml.erb, modules/roller/templates/prod/env.erb, modules/toplevel/manifests/worker.pp, modules/users/manifests/roller/account.pp, modules/users/manifests/roller/setup.pp, modules/users/templates/roller-allowed_commands.sh.erb
@dividehex @dragoscrisan 
1. fix network entries for fw module to add roller to iptables without trying to resolve the ips (I think the network firewall is only allowing ingress)
2. add "roller" user to Ubuntu workers with sudo for reboot
3. accept command "reboot" and not the full path
4. decrease the timeout for a reboot's is_down and is_up; If a reboot takes longer than a minute for the shutdown, then there is a problem and we can try a forced shutdown (like with ipmi/snmp).
=> Bug1457003 roller linux ssh

manifests/moco-config.pp, modules/fw/manifests/networks.pp
This is a bit transitional since it will list both the new and old DM under the fw module.  Once the dust has settled, we can remove the old DM from the fw network DM list.
=> Change distinguished puppet master

manifests/moco-config.pp, modules/scriptworker/manifests/instance.pp
=> bug 1470496 - use a single gpg key across all prod scriptworkers

modules/pushapk_scriptworker/files/requirements.txt
Follow up #80 which introduced https://tools.taskcluster.net/groups/T9NNzgxhSbmF1oNAhzwkFg/tasks/BQTUG7sIR2yvNbjkrksUjg/runs/0/logs/public%2Flogs%2Flive_backing.log#L27 
Tested against https://tools.taskcluster.net/groups/T9NNzgxhSbmF1oNAhzwkFg/tasks/BQTUG7sIR2yvNbjkrksUjg/runs/1
=> Downgrade prompt_toolkit to satisfy ipython reqs

.travis.yml
similar to #taskcluster-bots, going to move all releng bots to dedicated channel for now
=> Bug 1467026 - move travis-ci notifications to #releng-bots, r=testing

modules/nrpe/manifests/base.pp
This requires the nrpe Ubuntu package to be built with ssl enabled.
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1449745
=> Make sure nrpe uses SSL by default on Ubuntu 16.04

modules/nrpe/manifests/base.pp
When the default config file changes we should notify the nrpe service to restart and pick up the changes.
=> Restart nrpe service when ubuntu nrpe defaults changes

modules/packages/manifests/nrpe.pp, modules/packages/manifests/setup.pp
- Steps to  fix this error (this is a good occasion to create the package from nrpe 3.2.1-1 source):
- compiled the source with --enable-ssl=no flag
- named the package: nagios-nrpe-server_3.2.1-1_amd6_nossl.deb
- tested the package on Ubuntu 16.04 docker container: 
- intsaleld nagios_nrpe_server and nagios_nrpe_plugin packages:
- running: /usr/lib/nagios/plugins/check_nrpe -H 127.0.0.1
NRPE v3.2.1
=> Bug 1458468 - Update nrpe package on roller servers

modules/balrog_scriptworker/files/requirements-27.txt
Due to https://github.com/mozilla-releng/balrogscript/issues/37
(towncrier drops py2 support in 18.6.0)
=> pin towncrier to 18.5.0 in py2 venv

modules/signingserver/files/linux_requirements.txt, modules/signingserver/files/mac_requirements.txt, modules/signingworker/files/requirements.txt
These look really safe. gevent is the most notable upgrade, and its changelog doesn't show anything remotely scary.
=> Upgrade signingserver & signingworker python packages.

manifests/moco-config.pp
As part of migrating pypi to MDC1, we're only going to have a public pypi, no pvt any longer so remove references to it.
=> Bug 1476741: Only use pub pypi, not pvt

modules/signingserver/files/linux_requirements.txt, modules/signingserver/files/mac_requirements.txt
@escapewindow discovered that the system Mercurial is broken on the Mac signing servers today. This is a quick fix to get a working Mercurial on them. May as well do it on Linux as well, it might make the necessary documentation changes simpler.
=> Install Mercurial into signing server virtualenvs.

modules/mercurial/templates/hgrc.erb, modules/mercurial/templates/mercurial.ini.erb
According to @indygreg, there's no reason we should be disabling dotencode. It's been supported by Mercurial for a very, very, very long time (since 1.7 according to https://www.mercurial-scm.org/wiki/RequiresFile#Known_requirements, which was released in 2010). Disabling it means that robustcheckout ends up clobbering stuff a lot for correctness, which slows down a lot of operations (particularly on the new merge day instance).
This patch affects everything with Mercurial installed, as far as I can tell, but based on what I've been told and read it should be perfectly safe.
=> Stop disabling dotencode in Mercurial repos.

modules/signingserver/manifests/instance.pp
=> bug 1477434: Bump signcode maxsize to 350MB.

modules/signingserver/manifests/instance.pp
The fx-sig-verify tool also sets a maxsize. Keeping the two values in
sync avoids pages.
Related to #128
=> Doc secops interest in the signcode_maxsize value

modules/addon_scriptworker/files/requirements.txt, modules/balrog_scriptworker/files/requirements-3.txt, modules/beetmover_scriptworker/files/requirements.txt, modules/bouncer_scriptworker/files/requirements.txt, modules/buildbot_bridge/files/requirements.txt, modules/pushapk_scriptworker/files/requirements.txt, modules/pushsnap_scriptworker/files/requirements.txt, modules/releaserunner3/files/requirements.txt, modules/shipit_scriptworker/files/requirements.txt, modules/signing_scriptworker/files/requirements.txt, modules/signingworker/files/requirements.txt, modules/transparency_scriptworker/files/requirements.txt, modules/tree_scriptworker/files/requirements.txt
taskcluster-client.py 4.0.0 renames taskcluster.async to
taskcluster.aio, which is a breaking change. This commit pins our
version until we're ready.
=> pin taskcluster-client.py to <4.0.0 til we're ready

modules/toplevel/manifests/worker/releng.pp, modules/toplevel/manifests/worker/releng/generic_worker/test.pp
Missed to include packages::mozilla::python3 package to workers definition
=> Install python3.6 to OSX workers

.pyup.yml
After a discussion with @mozbhearsum we have concluded that for the next few weeks we should be doing PyUp merge requests on Thursdays, as Mondays are usually busy with Releases and Merges.
This will stay like this for a few weeks, while CiDuty learns the INs and OUTs about this task, and when the team becomes autonomous this weekly actionable will change either on Saturday or Sunday, when there is a lot less stuff happening. 
@lundjordan If you are okay with the change/plan (review+), Ben will be merging this into the master branch.
=> Update .pyup.yml to run every week on Wednesday

modules/generic_worker/templates/run-generic-worker.sh.erb
Now, each time when a worker who was in panic mode run jobs with success and reboot, update the closed auto generated bug. 
I corrected this, only after first job finished with success the bug will be updated and closed and the bug_id file will be deleted.
=> Bug 1479692 - Fix update bug if worker is in good state

.pyup.yml
SlaveAPI dashboard was been broken for a while now, to be exact when this PR [#71]( https://github.com/mozilla-releng/build-puppet/pull/71/files#diff-95780eb30d106e421159cda544ff09ec) landed, our dashboard started to encounter problems. 
PR https://github.com/mozilla-releng/build-puppet/pull/143 is planning to fix that, but with the current deployment, PyUp will keep suggesting for upgrades.
This dashboard will be used up to the point of BuildBot EOL. This file could also serve as a nice training ground for CiDuty to do manual changes (upgrades/downgrades).
Add the following lines, which will make PyUp ignore the SlaveAPI requirements text file:
```yml
requirements:
- modules/slaveapi/files/requirements.txt:
update: False
```
(based on docs found …
=> Ignore slaveapi/files/requirements.txt from weekly upgrades.

modules/signing_scriptworker/templates/dep-passwords.json.erb, modules/signing_scriptworker/templates/passwords.json.erb
```
10:48 <dividehex> ok. I noticed the ds workflows for dep and signing in mdc1 were broken. So I don't think they were ever initialized properly
*snip*
10:49 <aki> this is mac? or mac+linux?
10:49 <dividehex> i don't know how much work that creates on your side and I don't want to bomb you with that
10:49 <dividehex> this is mac only
10:50 <dividehex> linux is fune
10:50 <aki> ah. well, mac is having issues, so maybe that'll help
10:50 <dividehex> fine
10:50 <aki> how long will that take?
10:50 <aki> i can disable just mac and then reenable when you're done
10:51 <dividehex> I think it takes about 30m to go from DS to fully puppetized
10:51 <aki> ok. let me prepare a disable patch
10:51 <bhearsum> can you hold off on 10 for a short while? i want to finish trying something on it
10:51 …
```
=> disable mac mdc1 signing servers until we reimage

modules/signingserver/manifests/instance.pp
The system mercurial is busted on mac signing servers, but we can use the signing server instance's bin/hg to clone. We have to ssh in to start the signing servers anyway, so this may be an acceptable stopgap solution.
=> stop cloning tools automatically on mac signing servers due to bustage

modules/puppetmaster/templates/puppetmaster-pip-download.sh.erb
We're getting a bunch of e-mail (every 5 min x 2) about:
> You are using pip version 10.0.1, however version 18.0 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
This should stop the bleeding.
For reference we don't manage pip version for the download venv: https://dxr.mozilla.org/build-central/rev/9cb089f5a074bc4d138252914f3d07c8ad6e6229/puppet/modules/puppetmaster/manifests/data.pp#109
=> Disable pip version check to avoid cron spam eating up inboxes.

modules/generic_worker/manifests/init.pp
I ended up making the staging workers take production tasks because the "tc_environment" was set to staging, but the in-master module was looking for the variable named "environment".
So this applies the tc_environment to the workerType name set up.
=> Bug 1480412 - fix tc_environment var name

modules/addon_scriptworker/files/requirements.txt, modules/balrog_scriptworker/files/requirements-3.txt, modules/beetmover_scriptworker/files/requirements.txt, modules/bouncer_scriptworker/files/requirements.txt, modules/pushapk_scriptworker/files/requirements.txt, modules/pushsnap_scriptworker/files/requirements.txt, modules/shipit_scriptworker/files/requirements.txt, modules/signing_scriptworker/files/requirements.txt, modules/transparency_scriptworker/files/requirements.txt, modules/tree_scriptworker/files/requirements.txt
Re-enable scriptworker 15 and with taskcluster 4.0.1, which should fix the double-slash issue.
I plan on running this in my puppet env for a bit before rolling out to the rest of the pool.
=> Scriptworker15

modules/fw/manifests/profiles/mac_depsigning.pp, modules/fw/manifests/profiles/mac_signing.pp
This removes the host-based pf firewall rule allowing incoming vnc connections to mac-v2-signing and depsigning.  Also adds mdc2 to macsigning profile since it was missing. 👎
=> Bug 1482162: block vnc on mac-v2-signing and macdepsigning

modules/deploystudio/manifests/files.pp
The dir `/Deploy` is usually created by the deploystudio installer but puppet wants to pre-deploy some files there so let's make it so.  This should curb the puppet spam coming from the new deploystudio hosts.
=> Bug 1475616: create deploy dir for deploystudio

manifests/moco-config.pp
Once https://hg.mozilla.org/integration/autoland/rev/9d21ea9afe7a merges to m-c, we should update the bumpers to use the changes.
=> Don't generate trailing whitespace in `l10n-changesets.json`.

modules/addon_scriptworker/files/requirements.txt, modules/balrog_scriptworker/files/requirements-3.txt, modules/beetmover_scriptworker/files/requirements.txt, modules/bouncer_scriptworker/files/requirements.txt, modules/pushapk_scriptworker/files/requirements.txt, modules/pushsnap_scriptworker/files/requirements.txt, modules/shipit_scriptworker/files/requirements.txt, modules/signing_scriptworker/files/requirements.txt, modules/transparency_scriptworker/files/requirements.txt, modules/tree_scriptworker/files/requirements.txt
This depends on mozilla-releng/scriptworker#248 landing and [release 15.0.1](https://github.com/mozilla-releng/scriptworker/releases/tag/15.0.1) being made first, but I wanted to prepare this in advance to make less work for others! :-)
Will we also need to download the scriptworker release onto the distinguished puppet master?
@escapewindow Are there any deployments of scriptworker outside of puppet that I should also take care of?
Many thanks!
=> Bug 1486532 - upgrade scriptworker from 15.0.0 to 15.0.1

manifests/moco-nodes.pp
The plan here is to move bouncer_check from bm81 (scl3) to bm01 (use1). Since there are related nagios checks lets add to bm01 first, move the nagios checks separately, and then bm81 will get cleaned up with the rest of scl3.
=> Bug 1479619 - add bouncer_check on bm01

modules/addon_scriptworker/files/requirements.txt, modules/balrog_scriptworker/files/requirements-3.txt, modules/beetmover_scriptworker/files/requirements.txt, modules/bouncer_scriptworker/files/requirements.txt, modules/pushapk_scriptworker/files/requirements.txt, modules/pushsnap_scriptworker/files/requirements.txt, modules/shipit_scriptworker/files/requirements.txt, modules/signing_scriptworker/files/requirements.txt, modules/transparency_scriptworker/files/requirements.txt, modules/tree_scriptworker/files/requirements.txt
Reverts mozilla-releng/build-puppet#208
From IRC:
> tomprince: Scriptworker 16.0 is going to cause release tasks to retry endlessly (it doesn't handle that relpro actions aren't hooks) so we should probably back it out before starting any releases.
> ...
> tomprince: Just need to revert the build-puppet commit that upgraded things.
> rail: revert https://github.com/mozilla-releng/build-puppet/pull/208?
> tomprince: Yeah.
=> Revert "scriptworker 16.0.0"

modules/mig/manifests/agent/daemon.pp
This reverts commit b2e01fb8c3362f062d89315b94118c9175825f81. (Bug 1489603)
New installs on Ubuntu get stuck because puppet tries to restart mig-agent before mig-agent service is set up and fails.
=> Revert "Bug 1489603: let systemd restart mig after an upgrade"

manifests/moco-nodes.pp, modules/signing_server_cert_check/files/cert_check.sh, modules/signing_server_cert_check/files/check_sign_srv_ssl_exp.sh, modules/signing_server_cert_check/manifests/cron.pp, modules/signing_server_cert_check/manifests/init.pp, modules/toplevel/manifests/mixin/signing_server_cert_check.pp
This moves the signing server cert check to its own module, and runs it on the remaining buildbot masters (two, for redundancy) - which lets us kill cruncher.
=> Move cert check to two buildbot master hosts

modules/packages/manifests/libsodium.pp, modules/packages/manifests/setup.pp, modules/packages/manifests/xdelta3.pp, modules/packages/manifests/xdelta3.spec, modules/pushsnap_scriptworker/files/requirements.txt, modules/pushsnap_scriptworker/manifests/init.pp
I rebuilt the dependency list with https://github.com/mozilla-releng/pushsnapscript/pull/13. Maybe bumping some of the deps caused [bug 1488396](https://bugzil.la/1488396). I'm looking into it.
=> Bug 1488396 - Update pushsnap_scriptworker to latest snapcraft

modules/toplevel/manifests/server/signing.pp
Tested on mac-v2-signing13. This should hopefully reduce the churn on the mac signing servers, speeding things up. We can look at our numbers post-concurrency-tweak and compare.
Not sure if we need to restart the servers after this.
=> 10.10 concurrency 2

modules/signing_scriptworker/templates/passwords-mobile.json.erb
this is a no-op as right now, autograph-external points to autograph. we will be switching the autograph DNS over to an internal only LB in the future, hence this change.
=> mobile: use autograph-external domain

modules/fw/manifests/networks.pp, modules/fw/manifests/profiles/log_aggregator.pp, modules/fw/manifests/roles/syslog_from_mtv2_qa.pp
This commit modifies the fw module to allow syslog traffic from
the qa network in mtv2 to reach the mdc1 and mdc2 releng log
aggregators which in turn forward to papertail at this time.
This is in addtion to the network acls managed by netops.
=> Bug 1490875: fw allow syslog from qa.mtv2 to mdc1/2

modules/packages/manifests/mozilla/python3.pp, modules/packages/manifests/mozilla/python3.spec, modules/packages/manifests/setup.pp
This patch allows for a python 3.6.5-2 with lzma support. (That, in turn, unblocks the use of mardor in signingscript.)
I've tested this: signingscript-with-hash-signing works when testing https://github.com/mozilla-releng/signingscript/pull/69 using this custom build of python. I also tested against the current signingscript, after I uninstalled `xz-devel`; that appears to still work, though I haven't tested on a pristine environment (installing and uninstalling xz-devel may leave some cruft?). The main downside of this patch is that the scriptworkers delete their virtualenvs when this lands, leading to lengthy downtimes. We'll want to land when the tree is fairly quiet.
=> Lzma python

modules/mercurial/templates/hgrc.erb, modules/mercurial/templates/mercurial.ini.erb
Copy and paste from [bug 1495464 comment #6](https://bugzilla.mozilla.org/show_bug.cgi?id=1495464#c6). I'm pretty sure that mercurial.ini is unused now that we don't run any Windows builders but update it to the v3.9+ style config too. 
Also removes ftp-ssl.mozilla.org, which is baffling in an hg config file.
=> Update hg server cert for bug 1495464

manifests/moco-nodes.pp
Move back mdc2 nodes from gecko-t-linux-talos-tw queue to gecko-t-linux-talos queue and run generic-worker
=> move_back_mdc2_nodes_from_gecko-t-linux-talos-tw_to_gecko-t-linux-talos

modules/signing_scriptworker/files/requirements.txt
We had this pinned in signingscript, but we should be able to upgrade.
https://github.com/mozilla-releng/signingscript/commit/febe8842da6b5ca00d7fe332caa37bc4f1473925#r30817586
=> unpin datadog

modules/scriptworker/templates/check_pending_scriptworker_tasks.erb
There are probably nicer ways to fix this, but this should get nagios alerts fixed sooner.
=> add `taskcluster_root_url` to fix taskcluster>=5.0.0

modules/toplevel/manifests/mixin/l10n_bumper.pp
This isn't pretty, but this fixes the missing ssh key until we can move
l10n bumper to treescript.
Fixes the bustage from #225.
Tested on bm01.
=> bug 1499217 - fix l10n bumper

manifests/moco-config.pp
update the gecko revision to the landing of the initial patch from bug 1499809.
=> bug 1499809 - l10n bumper should touch a file on success.

modules/signing_scriptworker/templates/passwords-mobile.json.erb
After making this patch, I realized I need to update the decision task in Focus too. Signingscript know whether to contact autograph only if the format starts with `autograph_`: https://github.com/mozilla-releng/signingscript/blob/eb321067005541f3fcdf65e9375aef7f4f20ff5f/signingscript/utils.py#L169
=> Bug 1492245 - part 1: Allow Focus signing via autograph

modules/shipit_scriptworker/manifests/settings.pp
The release-mark-as-shipped task for Thunderbird has new scopes
assigned to it. This patch updates the scriptworker configuration
to recognize those scopes, preventing the 'This worker is not configured
to handle scope "project:comm:thunderbird:releng:ship-it:server:production"'
error when run.
=> Bug 1481203 - allow worker to use new thunderbird ship-it scopes

modules/signing_scriptworker/files/requirements.txt
Depends on https://github.com/mozilla-releng/signingscript/pull/95
=> Bug 1492245 - Bump signingscript to 9.5.1

manifests/moco-config.pp
Using fake values in case we don't hablde empty arrays properly
=> Bug 1511145: don't handle Firefox in releaserunner3

modules/pushapk_scriptworker/manifests/init.pp, modules/pushapk_scriptworker/manifests/jarsigner_init.pp, modules/pushapk_scriptworker/manifests/settings.pp
When extracting product name from scopes, hyphens are used. Therefore, product names are made of hyphens, not underscores.
=> Updates pushapk product names to have hyphens, not underscores

modules/pushapk_scriptworker/manifests/settings.pp
`$google_play_accounts_config_content` should always refer to content from `$google_play_config`, even for dep.
The issue this resolves is that `dep`'s `certificate` should point to a real file, not "dummy", and the `dep` `$google_play_config` properly specifies a real file
=> Updates Pushapk dep g_p_a_config_content to always reference g_p_config

modules/pushapk_scriptworker/manifests/settings.pp
I replaced all `reference-browser` usages to use `-`, just like how the product is represented in scopes. However, hiera secrets' keys should use underscores, not dashes. This PR properly makes sure that `-` and `_` are used consistently throughout `pushapk_scriptworker`
=> Uses underscores for hiera content

modules/signing_scriptworker/templates/passwords-mobile.json.erb
Before this patch: https://tools.taskcluster.net/groups/MddUus-YTaGD80Vfqk1fXA/tasks/SFSLXBWFTmGERPahGhRZ2Q/runs/0/logs/public%2Flogs%2Flive_backing.log#L26
After: https://tools.taskcluster.net/groups/MddUus-YTaGD80Vfqk1fXA/tasks/SFSLXBWFTmGERPahGhRZ2Q/runs/1/logs/public%2Flogs%2Flive_backing.log#L14
I manually edited the file on the worker to get the second run passing. r? @mitchhentges
=> reference-browser: Fix signing format

modules/signingserver/manifests/instance.pp
Bump by current attempt (370,758,144.00) rounded to 371,000,000. with an extra 2% added ontop.
This is similar in mindset to 1417497
=> Bug 1515335 - win64 asan failing to sign xul.dll due to size.

modules/pushapk_scriptworker/manifests/settings.pp
Reverts mozilla-releng/build-puppet#343 because of bug 1516105, it broke publishing to the play store.
=> Revert "Removes schema_file from pushapk config"

modules/addon_scriptworker/files/requirements.txt, modules/balrog_scriptworker/files/requirements-3.txt, modules/beetmover_scriptworker/files/requirements.txt, modules/bouncer_scriptworker/files/requirements.txt, modules/pushapk_scriptworker/files/requirements.txt, modules/pushsnap_scriptworker/files/requirements.txt, modules/shipit_scriptworker/files/requirements.txt, modules/signing_scriptworker/files/requirements.txt, modules/transparency_scriptworker/files/requirements.txt, modules/tree_scriptworker/files/requirements.txt
This will roll out release promotion action hook support. [changelog](https://github.com/mozilla-releng/scriptworker/pull/286/commits/c8c416e70e3e796449c639876a9dd12307829512#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)
=> bump scriptworker to 17.1.0

manifests/moco-config.pp
`mobile_shortlist` is equivalent to `shortlist`, plus `mhentges` added
=> Adds more-open mobile_shortlist for mobile signing workers

modules/pushapk_scriptworker/files/requirements.txt
This package passed at https://tools.taskcluster.net/groups/frz3aHJdTGOgKx7xCDKkmw/tasks/COm1E5W_Tc2K4Cerkorg6Q/runs/2/logs/public%2Flogs%2Flive_backing.log#L206
=> Bug 1368484 - part 2: Bump mozapkpublisher to 0.13.0

modules/addon_scriptworker/files/requirements.txt, modules/balrog_scriptworker/files/requirements-3.txt, modules/beetmover_scriptworker/files/requirements.txt, modules/bouncer_scriptworker/files/requirements.txt, modules/pushapk_scriptworker/files/requirements.txt, modules/pushsnap_scriptworker/files/requirements.txt, modules/shipit_scriptworker/files/requirements.txt, modules/signing_scriptworker/files/requirements.txt, modules/transparency_scriptworker/files/requirements.txt, modules/tree_scriptworker/files/requirements.txt
This has the `clientId` fix, as well as not retrying on 404 download errors.
=> bug 1521264 - scriptworker 18.0.1

modules/roller/templates/prod/worker_config.json.erb
mac #189 is broken (no display) and off warranty
https://bugzilla.mozilla.org/show_bug.cgi?id=1472510
=> remove t-yosemite-r7-189 from roller config

modules/signing_scriptworker/templates/dep-passwords.json.erb
Looks like I pasted the last line twice, then edited.
* https://github.com/mozilla-releng/build-puppet/pull/393
* hiera: pasword -> password
* this patch
=> bustage fix #3

modules/scriptworker/templates/supervisor_config.erb
Until [this PR](https://github.com/mozilla-releng/scriptworker/pull/310) is merged, this will just delay puppet sync times.
After that PR is merged, this allows "worker shutdown" to be propagated to Taskcluster
=> Bumps supervisord time before scriptworker is killed

modules/addon_scriptworker/files/requirements.txt, modules/balrog_scriptworker/files/requirements-3.txt, modules/beetmover_scriptworker/files/requirements.txt, modules/bouncer_scriptworker/files/requirements.txt, modules/pushapk_scriptworker/files/requirements.txt, modules/pushsnap_scriptworker/files/requirements.txt, modules/shipit_scriptworker/files/requirements.txt, modules/signing_scriptworker/files/requirements.txt, modules/transparency_scriptworker/files/requirements.txt, modules/tree_scriptworker/files/requirements.txt
Scriptworker now reports `worker-shutdown` if the task is terminated.
[`19.0.0` changelog](https://github.com/mozilla-releng/scriptworker/blob/master/CHANGELOG.md#1900---2019-02-13)
=> Bumps scriptworker version to 19.0.0

modules/scriptworker/templates/supervisor_config.erb
[We backed out this commit earlier](https://github.com/mozilla-releng/build-puppet/commit/55460dcd27b4eac26eda648cfa4081f8b234990b), but that turned out to be due to [timing, not the contents themselves](https://bugzilla.mozilla.org/show_bug.cgi?id=1529432)
=> Bumps supervisord time between terminating and killing scriptworker

modules/beetmover_scriptworker/templates/script_config.json.erb
This is for [this ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1522581). An earlier fix for the issue bumped the default maximum file size, but we missed the explicit override in puppet.
Since we don't _want_ a different maximum size, perhaps we can just lean on the default instead?
(If we'd rather be explicit in puppet, we should remove the default from `beetmover` and make it "required", imho)
=> Bumps beetmover max zip file size to 100mb

modules/signingserver/manifests/instance.pp
Bug 1530127
Perma signingscript.exceptions.FailedSubprocess: Command `/builds/scriptworker/bin/signtool -v -n /builds/scriptworker/work/nonce -t /builds/scriptworker/work/token ... builds/scriptworker/work/zipkaeu9jdb/firefox/xul.dll` failed
=> Perma Failing signing nightly asan

manifests/moco-config.pp, modules/addon_scriptworker/files/requirements.txt, modules/balrog_scriptworker/files/requirements-3.txt, modules/beetmover_scriptworker/files/requirements.txt, modules/bouncer_scriptworker/files/requirements.txt, modules/pushapk_scriptworker/files/requirements.txt, modules/pushsnap_scriptworker/files/requirements.txt, modules/scriptworker/manifests/chain_of_trust.pp, modules/scriptworker/manifests/instance.pp, modules/scriptworker/templates/scriptworker.yaml.erb, modules/shipit_scriptworker/files/requirements.txt, modules/signing_scriptworker/files/requirements.txt, modules/transparency_scriptworker/files/requirements.txt, modules/tree_scriptworker/files/requirements.txt
We probably have to deal with https://github.com/mozilla-releng/pushsnapscript/pull/18 before we can roll this out.
=> roll out scriptworker 22 with ed25519

modules/mercurial/files/robustcheckout.py
Recent versions of robustcheckout include new metrics output
and compatibility with newer versions of Mercurial. This commit
vendors the latest robustcheckout from version-control-tools,
revision 8e3bb142dfa9.
=> Bug 1535011: vendor latest `robustcheckout` from version-control-tools

modules/fw/manifests/profiles/mac_signing.pp
I'd like to generate the cert for pkg signing before 10.14.5 is released and need to use the Keychain via VNC to do so.
=> Temporarily re-allow VNC on mac-v2-signing

modules/pushapk_scriptworker/files/requirements.txt
This should allow Focus builds to be published again
=> Updates mozapkpublisher to 2.0.2

modules/nrpe/manifests/base.pp
This is a followup patch after seeing Warning: Unrecognised escape sequence '\/' in file /home/travis/build/mozilla-releng/build-puppet/modules/nrpe/manifests/base.pp at line 53 in last travis ci build at line 506-512. This warning came up in travis ci building of #460. Talked with @JohanLorenzo in #ci irc channel about the warning and this PR should solve the issue.
=> Use simple quotes instead of double quotes in /nrpe/manifests/base.pp

manifests/moco-config.pp, modules/config/manifests/base.pp, modules/packages/manifests/setup.pp, modules/packages/manifests/telegraf-dmg.sh, modules/packages/manifests/telegraf.pp, modules/telegraf/manifests/config.pp, modules/telegraf/manifests/install.pp, modules/telegraf/manifests/service.pp, modules/toplevel/manifests/worker.pp, modules/users/manifests/telegraf.pp
Adding the telegraf daemon to the hardware workers.
1. adds telegraf config into toplevel/worker
2. updates telegraf module for MacOS install and service control
3. adds a separate user for telegraf to run under
4. includes the build script for the MacOS dmg
=> Telegraf on hw workers

modules/pushapk_scriptworker/manifests/jarsigner_init.pp, modules/pushapk_scriptworker/manifests/settings.pp
I'm debugging [this failure](https://tools.taskcluster.net/groups/epmNm9N2S2CdmSE1kmcYcA/tasks/c9Cl2hQPT26UEx2cOZ_Gxw/runs/0/), and I was trying to grok the `pushapk` config.
Inlining these values should make them easier to interpret.
=> Inlines $jarsigner_all_certificates

modules/pushapk_scriptworker/files/requirements.txt, modules/pushapk_scriptworker/manifests/init.pp, modules/pushapk_scriptworker/manifests/jarsigner_init.pp, modules/pushapk_scriptworker/manifests/settings.pp
This is needed for the Fenix Beta to be pushed to the Google Play Store
Details: Allows Fenix to supply the certificate alias as a task payload, so `pushapk_scriptworker` doesn't infer it from scopes.
Bugging you Aki because Johan is away and you're a cool guy :)
=> Removes Fenix from jarsigner aliases

modules/pushapk_scriptworker/files/requirements.txt, modules/pushapk_scriptworker/manifests/settings.pp
This does three things:
* Updates `pushapkscript` so that using `certificate_alias` doesn't throw a schema-validation error
* Adds `has_nightly_track` to configs that were missing it, since it's required
* Adds a base `fenix` product config because it's inferred from scope, and we don't have separate `project:mobile:...:fenix-$channel` scopes
=> Resolve fenix nightlies failing

modules/toplevel/manifests/worker.pp
with puppetagain, perms on the puppet directory
allow only puppet or root to read the last-
run-summary.yml. for now, keep the permissions
=> remove telegraf input for puppetagent

modules/pushapk_scriptworker/manifests/settings.pp
Fenix [provides `certificate_alias` in the payload](https://taskcluster-ui.herokuapp.com/tasks/dxlTj-sVRvGjtKl35EnKAw), so it must be removed from the config, otherwise the build fails.
(this will be made obsolete by #483, but it fixes Fenix staging builds in the meantime)
=> Removes fenix from dep jarsigner certificate aliases

modules/signing_scriptworker/manifests/settings.pp
Previously, we turned off verbosity for both signing scriptworkers
(daemon) and signingscript (script) to avoid so much log spam from the
signing scriptworkers.
However, the former a) broke papertrail logging at all for the signing
scriptworkers, since `verbose` specifies whether scriptworker logs to
the screen, and b) broke nagios monitoring, since the claimWork call is
what keeps the logfile up to date when the daemon is idle.
This patch reverts only the scriptworker daemon part of the patch, back
to being verbose.
=> reenable verbose for signing scriptworkers

modules/signing_scriptworker/files/requirements.txt, modules/signing_scriptworker/templates/dep-passwords.json.erb, modules/signing_scriptworker/templates/passwords.json.erb
Reverts mozilla-releng/build-puppet#506
https://queue.taskcluster.net/v1/task/Aj_7jUC_RBmlNUM0eUL21Q/runs/0/artifacts/public/logs/live_backing.log
Not sure how I broke this -- I suspect the wheel isn't pulling in the right files.
=> Revert "Support signing via autograph omni.ja bundles."

modules/signing_scriptworker/templates/passwords-mobile.json.erb
When [bug 1556428](https://bugzilla.mozilla.org/show_bug.cgi?id=1556428) lands, merge this PR.
=> Signs fenix production/nightly with correct, unswapped key

manifests/moco-nodes.pp, modules/beetmover_scriptworker/files/requirements.txt, modules/signing_scriptworker/manifests/settings.pp, modules/signing_scriptworker/templates/dep-passwords-mobile.json.erb, modules/signing_scriptworker/templates/passwords-mobile.json.erb
Blocked on https://github.com/mozilla-releng/beetmoverscript/pull/226 roll-out to puppet Pypi.
=> Bug 1548545 - add support for gpg signing in beetmover's maven world

manifests/moco-config.pp
IT will turn off the graphite hosts since everyone is moving to other metrics collection.
remove setting of collectd_write in moco_config:
1. the graphite module uses this config variable as an on/off switch
2. metcollect (windows) module also turns on/off using this variable (but windows is not using build-puppet, right?)
=> bug 1561040 remove graphite write

modules/pushapk_scriptworker/manifests/settings.pp
The current `fenix` staging config only supports `org.mozilla.fenix`, which means that staging beta and nightly builds fail
=> Adds remaining fenix channels to pushapk dep config

modules/signing_server_cert_check/files/check_sign_srv_ssl_exp.sh
Future notices for the signing servers certificate expiration will be sent to the Relops email.
=> Updated notification email.

manifests/moco-config.pp
the accounts were already blocked from duo. This removes them
=> bug 1563081 remove ciduty users from jumphosts

modules/beetmover_scriptworker/files/requirements.txt
https://pypi.org/project/docutils/#files
We're getting puppet mail about this. I was able to download docutils-0.15.1.post1 and that fixed a manual install, but we need to land this change to stop getting puppet errors.
=> fix docutils

modules/beetmover_scriptworker/files/requirements.txt
The package name has `post1` in it, but evidently it's `0.15.1`:
`Requested docutils==0.15.1.post1 from https://files.pythonhosted.org/packages/d4/12/6c3fd74a590c7327c98cae008c11d536029fa9cd7924de477e8cb8804186/docutils-0.15.1-post1.tar.gz#sha256=f33ddb723332c6d6b6d99731ee1fc0c35eb4044a2df5cca1c64c8aa78eaf22cb, but installing version 0.15.1`
I think we either have to pin 0.14, or we can stop trying to download 0.15.1*. <s>This patch does the latter.</s> Tests are failing, so we're doing the former.
=> avoid puppet download docutils emails

test/verify-requirements.sh
.. until packaging fixes their warnings - https://github.com/pypa/packaging/issues/170
=> Pin pyparsing to 2.4.0 in tests

test/verify-requirements.sh
This reverts commit 185bf23f608fac22652d6eea25fd26afed273a7d, because pyparsing released 2.4.2 to squelch the warnings. See #564 for a link to their issue.
=> Revert "Pin pyparsing to 2.4.0 (#564)"

modules/addon_scriptworker/manifests/settings.pp
This allows us to rotate it (Per https://bugzilla.mozilla.org/show_bug.cgi?id=1573246) along with the password without having a period where stuff is broken.
=> Set amo user key to a secret

modules/addon_scriptworker/files/requirements.txt, modules/balrog_scriptworker/files/requirements.txt, modules/beetmover_scriptworker/files/requirements.txt, modules/bouncer_scriptworker/files/requirements.txt, modules/pushapk_scriptworker/files/requirements.txt, modules/shipit_scriptworker/files/requirements.txt, modules/signing_scriptworker/files/requirements.txt, modules/transparency_scriptworker/files/requirements.txt, modules/tree_scriptworker/files/requirements.txt
Deploys https://github.com/mozilla-releng/scriptworker/pull/388
r? @rail because I read you're interested in knowing all the changes done to puppet while you're deploying the new workers on GCP.
=> Bump scriptworker to 26.0.1

modules/signing_scriptworker/templates/passwords-mobile.json.erb
See [this Fenix ticket for context](https://github.com/mozilla-mobile/fenix/issues/4873).
I'll update the Fenix automation to produce a signing task with a payload like:
```
{
"upstreamArtifacts": [
{
"formats": [
"autograph_apk_fennec_sha1"
],
"paths": [...],
"taskId": "...",
"taskType": "build"
}
]
}
```
=> Adds signingscript configuration to sign fenix as fennec

modules/pushapk_scriptworker/manifests/settings.pp
This is for [this Fenix ticket](https://github.com/mozilla-mobile/fenix/issues/6461).
By changing `default_track` to `beta-closed`, releases will be pushed to the `beta-closed` track automatically
=> Changes Fenix beta target track to "beta-closed"

modules/generic_worker/manifests/init.pp, modules/generic_worker/templates/generic-worker.config.erb
Changes needed for moving workers to the new TC service on Saturday, Nov 9th.
1. new rootUrl
2. swap client id+token for linux and macos prod+staging workers.
_This will be held and merged during the tree-closing-window._
=> taskcluster client+token change for migration TCW

modules/packages/manifests/python2_zstandard.pp, modules/packages/manifests/python3_zstandard.pp, modules/packages/manifests/zstandard.pp, modules/packages/manifests/zstd.pp, modules/toplevel/manifests/worker/releng/generic_worker/test.pp
Also installs zstd CLI utility.
known issues:
- puppet < 4 doesn't support the same package name with two different providers, so exec must be used.
Testing done:
- converges locally in docker container
- converged successfully on t-linux64-ms-314 and t-linux64-ms-315
`puppet agent --test --server=releng-puppet2.srv.releng.mdc1.mozilla.com --environment=aerickson`
=> install zstandard pip for python 2 and 3

modules/log_aggregator/templates/client.conf.erb, modules/log_aggregator/templates/ubuntu_client.conf.erb
Papertrail does not show pids from incoming syslog entries. Security requested pids in the logs. So we can add the pid into the msg body for each.
This adds the pids into the message body for the linux64 workers.
=> add pids to syslog msg for ubuntu

modules/mercurial/files/robustcheckout.py
Updates to the latest robustecheckout, taken from changeset 102106f53cb2
in version-control-tools.
This version includes compatibility with the latest Mercurials,
Py3 support and some new metrics data.
=> Bug 1607614: update robustcheckout to latest, hg 5.2 compatible version

manifests/moco-config.pp
This will cause any puppet agent currently signed with one of the AWS puppetmasters to renew their agent certificate with different puppetmaster in the datacenters.  Which means the agent won't fail when the AWS puppetmaster intermediate certificate expires.  If we decide to renew/replace the puppetmasters intermediate CA, we can add them back to the list and they will become valid CAs to issue agent certificates again.
=> Bug 1614420: invalidate the use of the aws puppetmasters

manifests/moco-config.pp, modules/fw/manifests/profiles/log_aggregator.pp, modules/fw/manifests/roles/syslog_from_anywhere.pp
This redirects the hosts in AWS (if any) to use mdc1/2 for
puppetmasters and log aggregation in preperation of
decommisioning AWS releng puppetagain infra.
=> Begin redirecting AWS puppet agents and logs

modules/packages/manifests/mozilla/google_chrome.pp, modules/packages/manifests/setup.pp
*do not merge* (waiting on chromedriver changes)
running on "staging" group "-beta" for verification by qa team
```
[root@t-linux64-ms-444 ~]# /opt/google/chrome/chrome --version
Google Chrome 79.0.3945.117 unknown
[root@t-linux64-ms-444 ~]# puppet agent --test --server releng-puppet2.srv.releng.mdc1.mozilla.com --environment dhouse
Info: Retrieving pluginfacts
[...]
[root@t-linux64-ms-444 ~]# /opt/google/chrome/chrome --version
Google Chrome 80.0.3987.106 unknown
```
=> google chrome v80 on linux64

manifests/moco-config.pp
This remove the mdc1 puppetmasters from the valid puppet CA list which will cause all agents with certs issued from these hosts to renew their certs with one of the mdc2 hosts.  Once the mdc1 puppet masters have new CA certs, we can add them back.
=> Bug 1620424: remove mdc1 puppetmasters are valid CA issuers

manifests/moco-config.pp
MDC1 puppetmasters have new intermediate CA certs/keys and new master leaf certs/keys.  This will add them back to the vaild_puppet_cas list so agents can renew their certs more distributively among the puppetmaster CAs.
=> Bug 1620424: add mdc1 puppetmaster back to valid CA list

modules/packages/files/google-chrome.list, modules/packages/manifests/mozilla/google_chrome.pp
This is the repo file that chrome creates. I've put it into puppet to ensure puppet does not nuke it.
The at-least once weekly (when puppet is run) schedule is not ideal but will run less randomly than keystone :smiling_imp: _and_ not during tasks.
=> linux on moonshot - add google chrome repo and schedule check+update weekly

manifests/moco-nodes.pp
The -dev pool has not been used. We can re-create it when needed. https://bugzilla.mozilla.org/show_bug.cgi?id=1653992
=> remove linux -dev pool

manifests/moco-config.pp
This PR will cause any puppet agents with mdc2 puppet masters as their intermediate CA master to renew their agent cert with another valid CA, in this case either of the MDC1 puppet masters. It does not disable or prevent the agent from using either of the MDC2 puppet masters.  The purpose of this is ensure no agents are issued certs from a puppet master that may be turned off soon.  This includes MDC1 agents that may currently be issued certs from MDC2 intermediate CAs.
=> Invalidate mdc2 puppetmaster cas

manifests/moco-config.pp
This PR prepares any puppet agents in MDC2 to redirect their requests to the 2 mdc1 puppetmasters.  It also redirects syslog data to MDC1.
=> Redirect puppet catalog requests and syslog to mdc1

modules/fw/manifests/profiles/bsdpy.pp, modules/fw/manifests/profiles/deploystudio.pp, modules/fw/manifests/profiles/depsigning.pp, modules/fw/manifests/profiles/distinguished_puppetmaster.pp, modules/fw/manifests/profiles/linux_taskcluster_worker.pp, modules/fw/manifests/profiles/log_aggregator.pp, modules/fw/manifests/profiles/mac_depsigning.pp, modules/fw/manifests/profiles/mac_signing.pp, modules/fw/manifests/profiles/osx_taskcluster_worker.pp, modules/fw/manifests/profiles/partner_repack.pp, modules/fw/manifests/profiles/puppetmasters.pp, modules/fw/manifests/profiles/roller.pp, modules/fw/manifests/profiles/signing.pp, modules/fw/manifests/profiles/taskcluster_host_secrets.pp
In preparation of decommissioning the releng jumphosts, this PR allows ssh/vnc access directly from the corp vpn/jumphosts.  It covers all the hosts still managed under puppetagain.
=> Allow access to hosts without using jumphost
