mozilla-releng/build-puppet

- .pyup.yml
Pretty standard, except for the weekly schedule. I don't think we want to be restarting services every single day for updates, but I could be convinced otherwise.
> Add .pyup.yml.

- manifests/moco-nodes.pp
- modules/bouncer_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/manifests/init.pp
- modules/bouncer_scriptworker/manifests/settings.pp
- modules/bouncer_scriptworker/templates/script_config.json.erb
Depends on https://github.com/mozilla-releng/bouncerscript/pull/19
> Thunderbird bouncer workers.

- modules/beetmover_scriptworker/files/requirements.txt
I've completed steps 1-8 on the [release checklist](https://github.com/mozilla-releng/beetmoverscript/#deploy-a-new-version-to-production), just waiting on the new whl to be synced out.
> Deploy beetmover 7.4.0

- modules/buildbot_bridge/manifests/init.pp
The supervisor names are different than the bbb names =\
> Fix bbb stop commands.

- modules/roller/templates/dev/env.erb
- modules/roller/templates/prod/env.erb
https://bugzilla.mozilla.org/show_bug.cgi?id=1451470
to use the roller changes at https://github.com/mozilla-platform-ops/relops-hardware-controller/pull/81
> Roller reboot file bugzilla

- modules/config/manifests/base.pp
- modules/roller/templates/dev/env.erb
- modules/roller/templates/prod/env.erb
https://bugzilla.mozilla.org/show_bug.cgi?id=1451470
1. Use a new tag of roller in prod (will tag after https://github.com/mozilla-platform-ops/relops-hardware-controller/pull/82)
2. Make dev use the same reboot-bug template as prod.
> Roller adjust bug

- modules/packages/manifests/nrpe.pp
- modules/packages/manifests/setup.pp
Install nrpe 3.0 to roller servers
> Update nrpe package on roller servers

- modules/releaserunner3/templates/release-runner.yml.erb
https://phabricator.services.mozilla.com/D1832
> Bug 1455407: [releaserunner3] Specify the parameter prefix for getting revisions from comm-central builds.

- manifests/moco-nodes.pp
- modules/shipit_scriptworker/files/requirements.txt
To encompass changes from bug 1470228, 1472667.
> Bump shipitscript in shipitworkers.

- modules/packages/templates/tooltool.py
reason for this is that new `tooltool.py` uses new url
> Bug 1471541 - update tooltool to 1c6943c

- manifests/moco-nodes.pp
- modules/bouncer_scriptworker/files/requirements.txt
This is to land work from 1445946 (bouncer aliases and bouncer submission checks before and after the API updates)
> Bump bouncerscript in bouncerworkers.

- modules/aws_manager/files/requirements.txt
- modules/buildbot_bridge/files/requirements.txt
- modules/buildbot_bridge2/files/requirements.txt
- modules/buildduty_tools/files/requirements.txt
- modules/buildmaster/files/db_maintenance_requirements.txt
- modules/cruncher/files/allthethings_requirements.txt
- modules/cruncher/files/slave_health_requirements.txt
- modules/releaserunner/files/requirements.txt
- modules/selfserve_agent/files/requirements.txt
- modules/slaveapi/files/requirements.txt
- modules/slaverebooter/files/requirements.txt
Most of this is sqlalchemy+twisted. None of the changes are notable - I intend to just merge this when it's ready.
> Pick up latest round of upgrades for non-signing, non-scriptworkers

- modules/pushapk_scriptworker/files/requirements.txt
This wasn't caught in our CI due to the prose in PR #117
> Fix pushapk because of Bug 1476282

- modules/pushapk_scriptworker/files/requirements.txt
- modules/releaserunner/files/requirements.txt
- modules/signingworker/files/requirements.txt
- test/verify-requirements.sh
Lets see if this fixes the false-green
> Add pip check to enforce compatible requirements.

- modules/addon_scriptworker/files/requirements.txt
- modules/balrog_scriptworker/files/requirements-3.txt
- modules/beetmover_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushsnap_scriptworker/files/requirements.txt
- modules/shipit_scriptworker/files/requirements.txt
- modules/signing_scriptworker/files/requirements.txt
- modules/transparency_scriptworker/files/requirements.txt
- modules/tree_scriptworker/files/requirements.txt
Also bump taskcluster to 4.0.0 and stop preventing pyup from bumping it.
> scriptworker 15.0.0, signingscript 7.0.3

- manifests/moco-nodes.pp
Add 4 OSX and Linux workers to staging pools
> Added 4 OSX/Linux workers to staging pools

- manifests/moco-nodes.pp
- modules/shipit_scriptworker/manifests/init.pp
- modules/shipit_scriptworker/manifests/settings.pp
Depends on https://github.com/mozilla-releng/shipitscript/pull/7
> Add thunderbird shipit scriptworkers.

- modules/puppet/files/puppetize.sh
Turns out the mdc1/2 firewalls are blocking outgoing NTP traffic which is dropping the traffic to pool.ntp.org.  That's ok since we should be using internal NTP servers anyway.   I've redirected the `ntp.build.mozilla.org` cname to the MDC1 infobox host.  This host should be accessible from all internal releng networks.
> Bug 1480512: point puppetize.sh ntpdate at internal ntp host

- modules/beetmover_scriptworker/files/mime.types
- modules/beetmover_scriptworker/files/requirements.txt
- modules/beetmover_scriptworker/manifests/init.pp
- modules/beetmover_scriptworker/manifests/mime_types.pp
- modules/beetmover_scriptworker/manifests/settings.pp
- modules/beetmover_scriptworker/templates/base_script_config.json.erb
- modules/beetmover_scriptworker/templates/dev_script_config.json.erb
- modules/beetmover_scriptworker/templates/prod_script_config.json.erb
~~*Do not merge yet*. This needs to be tested e2e.~~
> Bug 1470942 - Add Maven-like bucket to beetmover

- .pyup.yml
Based on @mozbhearsum 's findings https://github.com/pyupio/pyup/blob/master/pyup/config.py#L11
> Fix capitalization of Wednesday for PyPu

- modules/beetmover_scriptworker/templates/prod_script_config.json.erb
> Bug 1470942 - part 2: Configure production bucket instead of staging one

- modules/bouncer_scriptworker/files/requirements.txt
Follow up https://github.com/mozilla-releng/bouncerscript/pull/39
> Bump bouncerscript

- manifests/moco-nodes.pp
- modules/bsdpy/manifests/init.pp
- modules/bsdpy/manifests/instance.pp
- modules/bsdpy/templates/docker-compose.yml.erb
- modules/toplevel/manifests/server/bsdpy.pp
This a simple module to set up bsdpy under docker.
> Bug 1484010: bsdpy module

- manifests/moco-config.pp
- modules/releaserunner3/templates/release-runner.yml.erb
* Get rid of devedition_pattern completely
* firefox_pattern should only accept releases and ESR
* remove releases/mozilla-beta from allowed_branches
> Bug 1490326 - releaserunner: disable betas

- manifests/moco-nodes.pp
> Bug 1474570 - Move workers from mdc1 to gecko-t-linux-talos-tw worker-type

- modules/signing_scriptworker/templates/dep-passwords.json.erb
- modules/signing_scriptworker/templates/passwords.json.erb
I think we want to switch to prod everywhere, including depsigning? I'll need to add some entries to Hiera before this lands.
> Switch to autograph prod.

- manifests/moco-config.pp
This grants me access to jump hosts, so that I can work on [bug 1475689](https://bugzil.la/1475689).
Jump host access request is raised in [bug 1492400](https://bugzil.la/1492400).
Many thanks!
> Bug 1492400 - grant pmoore access to jumphosts

- modules/addon_scriptworker/files/requirements.txt
- modules/balrog_scriptworker/files/requirements-3.txt
- modules/beetmover_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushsnap_scriptworker/files/requirements.txt
- modules/shipit_scriptworker/files/requirements.txt
- modules/signing_scriptworker/files/requirements.txt
- modules/transparency_scriptworker/files/requirements.txt
- modules/tree_scriptworker/files/requirements.txt
Update scriptworker from 15.0.4 to 16.0.1
> Update scriptworker from 15.0.4 to 16.0.1

- modules/beetmover_scriptworker/manifests/settings.pp
* add mobile-dev environment for later use
* fix aws credentials for naming consistency
> Bug 1495827 - Security fixes in beetmoverworker

- modules/beetmover_scriptworker/manifests/settings.pp
> Bug 1490367 - part 2: Switch maven prod to upload bucket

- modules/addon_scriptworker/files/requirements.txt
- modules/balrog_scriptworker/files/requirements-3.txt
- modules/beetmover_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushsnap_scriptworker/files/requirements.txt
- modules/shipit_scriptworker/files/requirements.txt
- modules/signing_scriptworker/files/requirements.txt
- modules/transparency_scriptworker/files/requirements.txt
- modules/tree_scriptworker/files/requirements.txt
Tested on canary depsigning-worker1, where I noticed I was missing `taskcluster-urls`. Now green.
> scriptworker 16.1.0, taskcluster 5.0.0

- modules/signingserver/templates/signing.ini.erb
This should allow signingserver to accept msi's
> Bug 1501453 - Allow signing of *.msi

- modules/packages/manifests/mozilla/osslsigncode.pp
- modules/packages/manifests/mozilla/osslsigncode.spec
- modules/packages/manifests/setup.pp
Ignore the pinning patch of this (for now) but if this looks good I'll deploy.
> Osslsigncode bump

- modules/fw/manifests/profiles/osx_taskcluster_worker.pp
- modules/toplevel/manifests/worker/releng/generic_worker/test.pp
Set up nrpe on the mac testers.
> Bug1496112 nrpe on mac workers

- modules/signing_scriptworker/files/requirements.txt
Follows https://github.com/mozilla-releng/signingscript/pull/88 up
> Bump signingscript to 9.4.0

- modules/balrog_scriptworker/files/requirements-27.txt
- modules/buildduty_tools/files/requirements.txt
- modules/pushapk_scriptworker/files/requirements.txt
- modules/signing_scriptworker/files/requirements.txt
- modules/signingserver/files/linux_requirements.txt
Once Reviewed and Merged, please remove the branch.
> BUG: 1507497 - Downgrade Cryptography back to 2.3.1

- manifests/moco-config.pp
This grants me access to jump hosts, so that I can work on bug 1508508.
Jump host access request is raised in bug 1509144.
Thanks!
> Bug 1509144 - grant mhentges access to jumphosts

- modules/signing_scriptworker/files/requirements.txt
- modules/signing_scriptworker/templates/dep-passwords.json.erb
- modules/signing_scriptworker/templates/passwords.json.erb
Depends on https://github.com/mozilla-releng/signingscript/pull/93
> Bug 1492245 - signing_scriptworker: Expose Fennec on Autograph

- modules/pushapk_scriptworker/files/requirements.txt
Depends on https://github.com/mozilla-releng/pushapkscript/pull/52
> Bug 1492245 - Bump pushapkscript to 0.9.0

- modules/pushapk_scriptworker/manifests/settings.pp
I didn't updated `pushapk_scriptworker/<snip>/settings.pp` as part of #303, but here it is now!
> Adds mobile-dep pushapk env config

- modules/addon_scriptworker/files/requirements.txt
- modules/balrog_scriptworker/files/requirements-3.txt
- modules/beetmover_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/files/requirements.txt
- modules/shipit_scriptworker/files/requirements.txt
- modules/signing_scriptworker/files/requirements.txt
- modules/transparency_scriptworker/files/requirements.txt
- modules/tree_scriptworker/files/requirements.txt
Depends on https://github.com/mozilla-releng/scriptworker/pull/278
> Bump scriptworker to 17.0.1

- modules/pushapk_scriptworker/manifests/jarsigner_init.pp
- modules/pushapk_scriptworker/manifests/settings.pp
https://bugzilla.mozilla.org/show_bug.cgi?id=1513675
> Indents all pushapk puppet config with 4 spaces

- modules/pushapk_scriptworker/manifests/settings.pp
This snuck into the `pushapk` `v0.10.0` release
> Resolves breaking change in pushapk interface

- modules/pushapk_scriptworker/files/requirements.txt
Depends on https://github.com/mozilla-releng/mozapkpublisher/pull/145
> Bump mozapkpublisher to 0.10.1

- modules/pushapk_scriptworker/manifests/settings.pp
See the [ticket](https://github.com/mozilla-releng/pushapkscript/issues/59) and [pushapk changes](https://github.com/mozilla-releng/pushapkscript/pull/64)
> Removes schema_file from pushapk config

- modules/addon_scriptworker/files/requirements.txt
- modules/balrog_scriptworker/files/requirements-3.txt
- modules/beetmover_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushsnap_scriptworker/files/requirements.txt
- modules/shipit_scriptworker/files/requirements.txt
- modules/signing_scriptworker/files/requirements.txt
- modules/transparency_scriptworker/files/requirements.txt
- modules/tree_scriptworker/files/requirements.txt
for https://github.com/mozilla-releng/scriptworker/pull/291 .
> scriptworker 17.1.1

- modules/balrog_scriptworker/files/requirements-27.txt
- modules/balrog_scriptworker/templates/script_config.json.erb
- modules/beetmover_scriptworker/files/requirements.txt
- modules/beetmover_scriptworker/manifests/settings.pp
- modules/beetmover_scriptworker/templates/script_config.json.erb
- modules/bouncer_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/templates/script_config.json.erb
- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/manifests/settings.pp
- modules/pushsnap_scriptworker/manifests/settings.pp
- modules/shipit_scriptworker/files/requirements.txt
- modules/shipit_scriptworker/manifests/init.pp
- modules/shipit_scriptworker/manifests/settings.pp
- modules/signing_scriptworker/templates/script_config.json.erb
I'm nervous about the large `shipitscript` version bump - this ticket is at some risk to cause breakage
> Don't explicitly set "schema_file" for scriptworker scripts

- modules/generic_worker/templates/run-generic-worker.sh.erb
- modules/packages/manifests/mozilla/py27_mercurial.pp
Add hg and python3 to PATH on OSX generic-worker
> Add hg and python3 to PATH on OSX generic-worker

- modules/pushapk_scriptworker/manifests/settings.pp
Adds config defined by [71](https://github.com/mozilla-releng/pushapkscript/pull/72)
> Adds "do_not_contact_google_play" for each of the pushapkscript instances

- modules/mig/manifests/agent/daemon.pp
Add "only-if" check for mig-agent restart to check for the service before trying to restart it.
* The mig-agent.service is not created until mig-agent has run (not set up in the installation package but by the binary itself).
* Systemctl restart mig-agent.service will return a failure exitcode and Puppet will then return a failure exist code.
Puppetize.sh will keep running puppet until it gets a truthy/0 exit, but mig-agent will never have been run and so the problem repeats.
> Bug 1489603: restart mig if exists

- modules/roller/templates/prod/worker_config.json.erb
dead logic board and off warranty: https://bugzilla.mozilla.org/show_bug.cgi?id=1505971
> remove t-yosemite-r7-048 from roller config

- modules/packages/manifests/mozilla/python3.pp
> Bug 1501497 - Install python 3.7.1 to OSX

- manifests/moco-nodes.pp
See https://bugzilla.mozilla.org/show_bug.cgi?id=1530732
> Allocate 4 osx nodes for level3 testers

- modules/shipit_scriptworker/manifests/settings.pp
Required by https://github.com/mozilla-releng/shipitscript/pull/23
> Add ship-it v2 settings

- manifests/moco-config.pp
This will disable all TB releases in releaserunner.
There will be another PR to remove releaserunener3. \o/
> Bug 1531141: disable TB in releaserunner

- modules/ssh/templates/sshd_config_duo.erb
Verify that OpenSSH configuration complies with guidelines
>  Bug 1129103 - Verify that OpenSSH configuration complies with guidelines

- modules/beetmover_scriptworker/files/mime.types
Fixes https://taskcluster-artifacts.net/I0xyvtmgQ22YDEkC64ZcPQ/0/public/logs/live_backing.log
> Bug 1450019 - beetmover: Define explicit MIME type for snap

- modules/balrog_scriptworker/manifests/settings.pp
- modules/balrog_scriptworker/templates/script_config.json.erb
Before I land this, I need to add the accounts to hiera.
> Add Balrog Auth0 secrets

- modules/balrog_scriptworker/files/requirements-27.txt
Before I merge this, I need to download the tarballs to puppet.
> Bump balrogscript/balrogclient version (Auth0)

- modules/nrpe/manifests/base.pp
Prevent restart nrpe service on every puppet run
> Bug 1500050 - Prevent restart nrpe service on every puppet run

- modules/addon_scriptworker/files/requirements.txt
- modules/balrog_scriptworker/files/requirements-3.txt
- modules/beetmover_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushsnap_scriptworker/files/requirements.txt
- modules/shipit_scriptworker/files/requirements.txt
- modules/signing_scriptworker/files/requirements.txt
- modules/transparency_scriptworker/files/requirements.txt
- modules/tree_scriptworker/files/requirements.txt
See https://github.com/mozilla-releng/scriptworker/pull/327
> Bump scriptworker to 23.0.1

- modules/fw/manifests/profiles/mac_signing.pp
This reverts commit 94d06ed73c7ed2ea48b72e50acaea6ab99295547. I'll merge this once I'm done.
> Revert "Temporarily re-allow VNC on mac-v2-signing (#452)"

- modules/fw/manifests/networks.pp
This reverts commit cc6863f14894cebbc65e76334690247a283b9d8d.
> Revert "add signing-linux-23"

- manifests/moco-nodes.pp
They have been working fine in GCP/cloudops for a few weeks now.
> Disable shipitworkers

- manifests/moco-config.pp
- modules/auditd/files/audisp-json.conf
- modules/auditd/manifests/init.pp
- modules/auditd/templates/audisp-json.conf.erb
- modules/config/manifests/base.pp
- modules/packages/manifests/audisp_json.pp
- modules/packages/manifests/setup.pp
add audisp-json 2.2.5-1 for centos6
> bug 1527145 audisp-json

- modules/addon_scriptworker/files/requirements.txt
- modules/balrog_scriptworker/files/requirements-3.txt
- modules/beetmover_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushsnap_scriptworker/files/requirements.txt
- modules/shipit_scriptworker/files/requirements.txt
- modules/signing_scriptworker/files/requirements.txt
- modules/transparency_scriptworker/files/requirements.txt
- modules/tree_scriptworker/files/requirements.txt
Fixes https://github.com/mozilla-releng/scriptworker/issues/331
> Bump scriptworker to 23.0.6

- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/manifests/init.pp
- modules/pushapk_scriptworker/manifests/settings.pp
> Pushapk config structure update

- modules/signing_scriptworker/files/requirements.txt
- modules/signing_scriptworker/templates/dep-passwords.json.erb
- modules/signing_scriptworker/templates/passwords.json.erb
This is ready to land now that I've tested locally the fix for vendoring.
> Re-bump signingscript to 11.0+ (11.0.1 in this case)

- modules/fw/manifests/profiles/mac_signing.pp
> Disable VNC again, reverting #516.

- modules/signing_scriptworker/templates/passwords.json.erb
> Bug 1559056 - Fix wrong instance in order to nightly-sign omni.ja

- modules/balrog_scriptworker/files/requirements-27.txt
- modules/balrog_scriptworker/files/requirements.txt
- modules/balrog_scriptworker/manifests/init.pp
- modules/balrog_scriptworker/manifests/settings.pp
> Updates balrogscript and runs in py3 environment

- modules/pushapk_scriptworker/manifests/settings.pp
Original error at: https://tools.taskcluster.net/groups/e68n6QPUSDa1pGpXmKREOQ/tasks/ZROAtGnmTkiY6ZXmMffR0A/runs/0/logs/public%2Flogs%2Flive_backing.log#L16
> Bug 1559115 - Fix dep-pushapk

- modules/beetmover_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/files/requirements.txt
To pick up 
* https://github.com/mozilla-releng/beetmoverscript/commit/c626c83bbfc023cfdfefc4a09f9b90461f19ec58
* https://github.com/mozilla-releng/bouncerscript/commit/535549a73eb30c29ecf33d1324f22a1cd024c0b3
> Deploy partner stub installer support

- modules/bouncer_scriptworker/files/requirements.txt
To deploy https://github.com/mozilla-releng/bouncerscript/pull/61
> Bouncerscript 3.6.1 - regression fix

- modules/auditd/manifests/init.pp
- modules/log_aggregator/manifests/init.pp
- modules/log_aggregator/templates/papertrail.conf.erb
json audit messages are being received correctly by mozdef
we can stop using the cef plugin
I tested this on log-aggregator2.[mdc1,mdc2]
> Bug1527145 remove audisp cef

- manifests/moco-nodes.pp
https://bugzilla.mozilla.org/show_bug.cgi?id=1563340
> Add tier3 bsdpy nodes

- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/manifests/settings.pp
Depends on https://github.com/mozilla-releng/pushapkscript/pull/95 and https://github.com/mozilla-releng/mozapkpublisher/pull/206
> Bug 1560876 - Bump {pushapkscript, mozapkpublisher} to {3.0.0, 4.0.0}

- modules/addon_scriptworker/files/requirements.txt
- modules/balrog_scriptworker/files/requirements.txt
- modules/beetmover_scriptworker/files/requirements.txt
- modules/bouncer_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushsnap_scriptworker/files/requirements.txt
- modules/shipit_scriptworker/files/requirements.txt
- modules/signing_scriptworker/files/requirements.txt
- modules/transparency_scriptworker/files/requirements.txt
- modules/tree_scriptworker/files/requirements.txt
- comm-esr68 support
- Allow actions to not pass parameters explicitly.
> Bump scriptworker.

- manifests/moco-config.pp
- modules/mig/manifests/agent/disable.pp
- modules/toplevel/manifests/jumphost.pp
- modules/toplevel/manifests/server.pp
- modules/toplevel/manifests/worker/releng.pp
https://bugzilla.mozilla.org/show_bug.cgi?id=1562061
> Disable mig

- modules/mig/manifests/agent/disable.pp
Fixes the kill mig darwin exec resource
> [bug 1562061] fix darwin kill mig-agent exec

- modules/signing_scriptworker/templates/dep-passwords.json.erb
Support swapping omnija to prod autograph
> Bug 1564264 - Move omnija dep signing to prod autograph

- modules/signing_scriptworker/files/requirements.txt
- modules/signing_scriptworker/templates/dep-passwords.json.erb
- modules/signing_scriptworker/templates/passwords.json.erb
This is built on top of PR #571
> Support Langpack Signing in Autograph for signingscript

- modules/toplevel/manifests/base.pp
- modules/toplevel/manifests/jumphost.pp
I was leaving the service un-controlled by puppet and so it was still enabled and running on hosts.
> disable collectd service

- modules/packages/manifests/mozilla/google_chrome.pp
- modules/packages/manifests/setup.pp
- modules/toplevel/manifests/worker/releng/generic_worker/test.pp
This is untested at the moment and there might be some dependencies that need to be installed or upgraded.  I'll test before merging of course.
> Install google chrome

- modules/pushapk_scriptworker/files/requirements.txt
- modules/pushapk_scriptworker/manifests/settings.pp
- modules/signing_scriptworker/templates/dep-passwords-mobile.json.erb
- modules/signing_scriptworker/templates/passwords-mobile.json.erb
This adds Firefox for Fire TV support to pushapkscript, and keys to signingscript.
> FirefoxTV support

- manifests/moco-config.pp
i don't think this list does anything. But, to continue house cleaning...
> removes mhentges from mobile shortlist

- manifests/moco-config.pp
Rok is out, Mitch has changed teams.
> Remove mhentges and rgabas from jumphosts

- modules/telegraf/templates/telegraf.conf.erb
- modules/toplevel/manifests/worker.pp
add cpu/temp/other monitoring on linux and macos workers
> Bug1588596 worker monitoring

- manifests/moco-config.pp
> Remove dcrisan from jumphost admins

- manifests/moco-nodes.pp
This removes a lot of hosts that don't exist anymore.
> Clean up moco nodes

- modules/packages/manifests/mozilla/ffmpeg.pp
- modules/packages/manifests/mozilla/imagemagick.pp
- modules/packages/manifests/setup.pp
- modules/toplevel/manifests/worker/releng/generic_worker/test.pp
This is not the portable/static build of imagemagick, but a copy of backports that tarek confirmed tests against.
> Bug1656965 linux testers imagemagick, ffmpeg

- modules/ntp/manifests/daemon.pp
for https://jira.mozilla.com/browse/IO-1811
> silence mac-whack-ntp
